config/routes.rb
Rails.application.routes.draw do

  get 'users/index'

  get 'users/show'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :posts do
    resources :comments
  end

  resources :users

  get '/profile/:user_id' => 'profile#show'

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	validates :content, presence: true

  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :posts
  has_many :comments

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

	def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    user.name = auth.info.name   # assuming the user model has a name
	    user.image = auth.info.image # assuming the user model has an image
	  end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.create(comment_params)
  	@comment.user = current_user
  	@comment.save
  	redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
  def comment_params
  	params.require(:comment).permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order(created_at: :desc)

  end

  def show
  	
  end

  def new
    @post = Post.new
  end

  def create
  	@post = Post.new(post_params)
  	@post.user = current_user

  	if @post.save
  		redirect_to @post.user
  	else
  		render 'new'
  	end
  end

  def edit

  end

  def update
  	if @post.update(post_params)
  		redirect_to @post
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@post.destroy
  	redirect_to posts_path
  end

  private

  def set_post
  	@post = Post.find(params[:id])
  end

  def post_params
  	params.require(:post).permit(:content)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def show
  	@user = User.find(params[:user_id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  def index
  end

  def show
  end

  private
  def set_post
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p>
	<%= link_to "/profile/#{comment.user.id}" do %>
		<strong><%= comment.user.name %></strong> 
	<% end %>
	<%= comment.content %>
	<% if comment.user == current_user %>
		<%= link_to 'Del', post_comment_path(comment.post, comment), method: :delete %>
	<% end %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>
		<%= f.text_field :content %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/layouts/_navbar.html.erb
<div style="border-bottom: 1px solid red">
	<%= link_to "Post list", posts_path %>
	<div style="float:right;">
	<% if user_signed_in? %>
	  <%= image_tag(current_user.image, size: '20x20', style:'border-radius:3px;vertical-align:top;') if current_user.image %>
		<%= link_to current_user.name, "/profile/#{current_user.id}" %>
		<%= link_to 'logout', destroy_user_session_path, method: :delete %>
	<% else %>
		<%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
	<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Betterlog</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <nav class="top-nav teal">
        <div class="nav-wrapper">
          <a href="#" data-activates="nav-mobile" class="button-collapse top-nav full hide-on-large-only"><i class="material-icons">menu</i></a>
          <a href="/posts" class="brand-logo right"><%= image_tag("logo.png") %></a>
        </div>
    </nav>
    <ul id="nav-mobile" class="side-nav fixed" style="transform: translateX(-100%);">
      <% if user_signed_in? %>
          <li><div class="userView teal darken-2">
            <a href="/users/<%= current_user.id %>">
            <!--<%= image_tag("image_card.jpg", class:"background",style: 'height:100%;width:100%;') %>-->
            <%= image_tag(current_user.image, size: '50x50', class:"circle") if current_user.image %>
            <span class="white-text name"><%= current_user.name %></span>
            </a>
            <%= link_to 'logout', destroy_user_session_path, method: :delete,:class => "white-text" %>
          </div></li>
      <% else %>
          <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
      <% end %>
      <!--<li><a href="#!" class="collection-item">Notification<span class="new badge">3</span></a></li>-->
      <!--<li><a href="#!">Jiyeon comment on you</a></li>-->
      <!--<li><a href="#!">Jiyeon send email to you</a></li>-->
      <!--<li><a>please push Today daily log</a></li>-->
    </ul>
  </header>

  <main>
      <div class="row pad-top-30">
        <div class="col s12 m12 l12 offset-l3">
          <%= yield %>
        </div>
      </div>
  </main>

  <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large teal" href="/posts/new">
      <i class="large material-icons">mode_edit</i>
    </a>
    <ul>
      <li><a class="btn-floating red"><i class="material-icons">insert_chart</i></a></li>
      <li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
      <li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
      <li><a class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>
    </ul>
  </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <div class="row">
	<div class="input-field col s12 m12 l8">
		<%= f.text_area :content, :id=>"textarea1",:class=>"materialize-textarea" %>
    <label for="textarea1">Content</label>
  </div>
    </div>

    <div class="row">
      <%= button_tag(type: 'submit', class: "btn-floating btn-small waves-effect waves-light teal") do %>
          <i class="small material-icons">mode_edit</i>
      <% end %>
    </div>
<% end %>

app/views/posts/_post.html.erb
<div class="col s12 m12 l8">
  <div class="card blue-grey darken-1">
    <div class="card-content white-text" style="padding:0px; padding-left: 10px;">
      <div class="card-title">
        <div class="chip">
          <a href="/users/<%= post.user.id %>">
            <%= image_tag(post.user.image) %>
            <%= post.user.name %>
          </a>
        </div>
        <div class="chip">
          <%= post.created_at.strftime("%m/%d/%y") %>
        </div>
      </div>

      <div class="card-content">
        <p><%= post.content %></p>
      </div>
    </div>


    <!--<div class="card-action">-->
    <!--<i class="small white-text material-icons comment-button">comment</i>-->
    <!--<i class="small white-text material-icons">email</i>-->
    <!--<div class="side-box">-->
    <!--<%= render post.comments %>-->
    <!--</div>-->
    <!--</div>-->
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>
<%= link_to 'Back', post_path(@post) %>a

app/views/posts/index.html.erb
<h5>main</h5>
<%= render @posts %>
<!--create button-->

app/views/posts/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
	<%= link_to "/profile/#{@post.user.id}" do %>
		<strong><%= @post.user.name %></strong>
	<% end %>
</p>
<p>
	<%= @post.content %>
</p>
<hr>
<h3>Comments</h3>
<%= render @post.comments %>

<%= render 'comments/form' %>

<%= link_to 'List', posts_path %> 
<% if @post.user == current_user %>
	| <%= link_to 'Edit', edit_post_path(@post) %> 
	| <%= link_to 'Delete', post_path(@post), method: :delete %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h5>user: <%= @user.name %></h5>
<%= render @posts%>